version: '3'

services:
  web:
    build: .
    ports:
      - "4000:8000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always

  redis:
    image: "redis:alpine"
    restart: always
